spring:
  application:
    name: edusale-server

  datasource:
    url: jdbc:sqlite:edusale.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  jackson:
    # ????????? ?????? ??? ? ???? ???????? ?????/??????????? ?? ???? ??????????
    write-date-timestamps-as-nanoseconds: false

server:
  port: 8080

jwt:
  secret: "your-secret-key-change-this-in-production-min-256-bits-long-for-security"
  # 24 ???? ? ?????????????
  expiration: 86400000
  # 7 ???? ? ?????????????
  refresh-expiration: 604800000
